### ISSUE TITLE
Implement a DiskLruCache that monitors the space used

### ISSUE THREAD

**Issue by eduardb** [danikula/AndroidVideoCache#5] opened 2015-06-09 14:10 UTC
As stated in `getExternalCacheDir()`'s [documentation](https://developer.android.com/reference/android/content/Context.html#getExternalCacheDir()), the platform usually doesn't clean the external cache directory automatically. Thus, something like a `DiskLruCache` where you could specify the maximum size that you want the cache to store would be very useful. JakeWharton's [DiskLruCache](https://github.com/JakeWharton/DiskLruCache) could be a very good starting point for this.

**Comment by danikula** [comment] 2015-06-09 16:46
@eduardb It is out of the scope of this library. But you can easy implement by yourself. Just implement 
`CacheListener`. When cache percentage achieve 100 just add cache file to the `DiskLruCache`

**Comment by danikula** [comment] 2015-06-22 16:07
I think it should be implemented in the next major version.

**Comment by nomad609** [comment] 2015-08-04 11:45
Hello Danikula,

Thanks for good library for Caching Video. 
I have one question, how to clear video cache from memory ?

ERROR: 
08-04 14:59:49.831    8860-8860/com.test.android D/MediaPlayer﹕ getMetadata
08-04 14:59:49.834    8860-8860/com.test.android I/TestScreen﹕ Video Duration 1: 10134Video Buffer Percentage100
08-04 14:59:49.848    8860-9724/com.test.android W/MediaHTTPConnection﹕ readAt 0 / 32768 => java.net.ProtocolException: Unexpected status line: ��i��N,��3�^�sE��C��N��3}�* /B3n�0���]�$�����C�(5���(
'��:ן���ݎf�P��Ĕ.���@C�(k\L.%�:)"�$%�{w��X�F����/.p.���G)�Z��EV�X
�m�;��Lt��`���o�h��	1��j1!�-���s,�d�E��|�;�vW>�$�M{��+�6Z�,�ZPI�4*���8#�d0�p3�`�o8�fg9���JƲ@E�dr��Ò҆4�\h����)Ѯt��^F������w���KsP^��$���#���~{ �+Py8M�X����
08-04 14:59:49.900    8860-8878/com.test.android E/MediaPlayer﹕ error (1, -1004)
08-04 14:59:49.905    8860-8860/com.test.android E/MediaPlayer﹕ Error (1,-1004)
08-04 14:59:49.905    8860-8860/com.test.android D/VideoView﹕ Error: 1,-1004
08-04 14:59:49.911    8860-9759/com.test.android D/Retrofit﹕ ---> HTTP GET http://myUrl/12345
08-04 14:59:49.911    8860-9759/com.test.android D/Retrofit﹕ ---> END HTTP (no body)
08-04 14:59:50.031    8860-9725/com.test.android E/MediaPlayer﹕ error (1, -1004)
08-04 14:59:50.031    8860-8860/com.test.android E/MediaPlayer﹕ Error (1,-1004)
08-04 14:59:50.031    8860-8860/com.test.android D/VideoView﹕ Error: 1,-1004
08-04 14:59:50.039    8860-9760/com.test.android D/Retrofit﹕ ---> HTTP GET http://myUrl/12345
08-04 14:59:50.040    8860-9760/com.test.android D/Retrofit﹕ ---> END HTTP (no body)
08-04 14:59:50.837    8860-9705/com.test.android D/ProxyCache﹕ Accept new socket Socket[address=/127.0.0.1,port=43002,localPort=45620]
08-04 14:59:50.843    8860-9769/com.test.android I/ProxyCache﹕ Request to cache proxy:

Once, this method returns onCacheDataAvailable(int cachePercentage) 100 , 101, 102

Any idea, why it is happening ?------  But Intermittent

My requirement, 
Screen -1 : Playing Video url (Some url )
Screen-2 : Playing video url (Same Url here too)

Please suggest me how to clear cache completely...

Thanks,
Anil

**Comment by danikula** [comment] 2015-08-05 12:27
@nomad609 To clean cache you can download file you passed to `FileCache`.
Can you share with me very simple basic project that help me reproduce issue you describe?

**Comment by nomad609** [comment] 2015-08-06 16:43
Thanks Danikula for reply :)

I can make sample example for it, but it is not coming frequently, but problem is weird means once it comes then it does n't allow to play same video again even after I destroy my app/ close it completely. I have only option to work it properly by FORCE CLOSE and CLEAR DATA of my App from mobile Settings.

I still exploring why it is happening:

Any idea in which situation this exception can come:

"MediaHTTPConnection﹕ readAt 0 / 32768 => java.net.ProtocolException: " 

I hope this might help to resolve it, I googled it but failed to reach any solution.

Thanks for helping me.

Thanks,
Anil

**Comment by nomad609** [comment] 2015-08-06 17:13
Currently clearing cache data by 

File dataFile = new File(mActivity.getExternalCacheDir(), mVideo_cache_name);
if (dataFile != null) {
      boolean deleted = dataFile.delete();
      Log.d(TAG, "CacheDeleted status  : " + deleted);
}

"deleted" returns true, but once the above exception comes then it is also not working, 

please suggest me another way to clear cache data completely by codes.

Thanks,
Anil

**Comment by vedant1811** [comment] 2015-09-25 13:44
@danikula What is the status of this issue?

I want to implement this by imposing a limit on the max cache size (say 100MB). If the cache size exceeds this, the last accessed cache file should be deleted.

Give me your thoughts so that I can start working on this and submit a PR soon.

Thanks.

**Comment by danikula** [comment] 2015-09-25 17:41
@vedant1811 I've not started to implement it yet because I haven't full vision how to implement it in the best way.

**Comment by vedant1811** [comment] 2015-09-29 06:36
@danikula A good way to implement this would be to to delete the last un-accessed files in cache when the total cache size exceeds a specified limit.
I do not have idea of your source code, but would this be easy to implement?

**Comment by danikula** [comment] 2015-09-29 06:45
@vedant1811 I agree with you. I want to use [JakeWharton's DiskLruCache](https://github.com/JakeWharton/DiskLruCache), but it has inappropriate API for me. So I have to fork it or implement from scratch. This issue has priority number one for me.

**Comment by vedant1811** [comment] 2015-09-29 11:01
@danikula I think that would be overkill for our purpose. We need a simple LRU.
Also, this is a priority for me as well. I am using your library in production for an app that is soon (in 2 months) to be launched on the play store :)

**Comment by danikula** [comment] 2015-10-23 12:06
added in 2.3.0

**Closed by danikula** 2015-10-23 12:06 UTC
Labels: enhancement
